In [4]:
import numpy as np

def ecludDist(inA, inB):
    distance = np.sqrt(np.sum((inA-inB)**2, 0))
    return distance

x1 = np.array([[0],[0]])
x2 = np.array([[3],[4]])

ecludDist(x1, x2)

array([5.])

In [5]:
ecludDist([1,0],[0,1])

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [19]:
(x1 - x2)**2

array([[ 9, 16]], dtype=int32)

In [114]:
import numpy as np

def ecludDist(inA, inB):
    distance = np.sqrt(np.sum((inA-inB)**2, 1))
    return distance

def dist(point, group):
    dist_list = list(np.argsort(list(ecludDist(point, group))))    
    return dist_list

def knn(test, train, labels, k=0):
    ret_labels = []
    if k == 0:
        k = int(np.sqrt(len(train))) 
    
    for td in test:
        ret_labels = labels[dist(x,gr)[:k]]
    
    dic_labels = {}
    for la in ret_labels:
        try:
            dic_labels[la] += 1
        except:
            dic_labels[la] = 1
    
    sort_labels = sorted(dic_labels.items(), key=lambda x: x[1], reverse=True)
    return tuple(sort_labels)[0][0]
 

x = np.array([[0,0]])
gr = np.array([[4,4],[3,3],[2,2],[1,1]])
labels = np.array(['A','A','B','B'])
k = 3
print(labels[dist(x,gr)[:k]])


print(knn(x,gr,labels, 3))

['B' 'B' 'A']
B


In [64]:
ecludDist(x,gr)

array([5.65685425, 4.24264069, 2.82842712, 1.41421356])

In [40]:
np.argsort([1,5,3])

array([0, 2, 1], dtype=int64)

In [79]:
dataset = np.loadtxt("datingTestSet2.txt", delimiter='\t', dtype='float16')

In [80]:
dataset.shape

(1000, 4)

In [81]:
dataset[0:5,:]

array([[4.093e+04, 8.328e+00, 9.541e-01, 3.000e+00],
       [1.449e+04, 7.152e+00, 1.674e+00, 2.000e+00],
       [2.605e+04, 1.441e+00, 8.052e-01, 1.000e+00],
       [      inf, 1.315e+01, 4.290e-01, 1.000e+00],
       [3.834e+04, 1.670e+00, 1.343e-01, 1.000e+00]], dtype=float16)

In [86]:
trainData = dataset[0:900,0:3]
trainLabels = dataset[0:900,3]
testData = dataset[900:,0:3]
testLabels = dataset[900:,3]

In [90]:
print(trainData.shape, trainLabels.shape, testData.shape, testLabels.shape)

(900, 3) (900,) (100, 3) (100,)


In [95]:
trainLabels[dist(testData[0,:],trainData)[:30]]

C:\Users\ilifo\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in square
  after removing the cwd from sys.path.


array([3., 3., 3., 1., 3., 1., 1., 1., 1., 2., 1., 3., 1., 2., 3., 3., 1.,
       3., 1., 1., 2., 2., 2., 3., 2., 2., 2., 1., 1., 3.], dtype=float16)

In [ ]:
knn(testData, trainData, trainLabels, 30)