In [3]:
import tensorflow as tf

In [9]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)
d = tf.multiply(a,b)
e = tf.add(c,b)
f = tf.subtract(d,e)

sess = tf.Session()

outs = sess.run(f)

sess.close()

print(f'outs = {outs}')

outs = 5


In [16]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.multiply(a,b)
d = tf.pow(c,2)
e = tf.divide(a,d)

with tf.Session() as sess:
    fetches = [a,b,c,d,e]
    outs = sess.run(fetches)

print(f'outs = {outs}')

outs = [5, 2, 10, 100, 0.05]


In [22]:
a = tf.constant([[1,2,3],[4,5,6]])
print(a.get_shape())

(2, 3)


In [23]:
x = tf.constant([1,0,1])
print(x.get_shape())

(3,)


In [24]:
x = tf.expand_dims(x,1)
print(x.get_shape())

(3, 1)


In [26]:
b = tf.matmul(a,x)
print(b)
sess = tf.InteractiveSession()
print(f'matmul : \n {b.eval()}\n')

Tensor("MatMul_2:0", shape=(2, 1), dtype=int32)
matmul : 
 [[ 4]
 [10]]



In [31]:
import numpy as np

x = np.array([1,0,1])
print(x.shape)

(3,)


In [32]:
a= tf.constant([[1,2,3,],[4,5,6]])
x = x[:,np.newaxis]
print(x.shape)

b= tf.matmul(a,x)

print(f'matmul : \n {b.eval()} \n')

(3, 1)
matmul : 
 [[ 4]
 [10]] 



In [40]:
val = tf.random_normal((1,5),0,1)
var = tf.Variable(val, name='var')

print(f'pre run : \n{var}')

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    post_var = sess.run(var)
print(f'\npost_var : \n{post_var}')

pre run : 
<tf.Variable 'var_7:0' shape=(1, 5) dtype=float32_ref>

post_var : 
[[ 0.6790799  -1.5709827  -1.2404418  -0.21053384  1.1134106 ]]


In [50]:
x_data = np.random.randn(5,10)
w_data = np.random.randn(10,1)


with tf.Graph().as_default():
    x = tf.placeholder(tf.float32, shape=(5,10))
    w = tf.placeholder(tf.float32, shape=(10,1))
    b = tf.fill((5,1), -1.)
    xw = tf.matmul(x,w)
    xwb = xw + b
    
    s = tf.reduce_max(xwb)
    with tf.Session() as sess:
        outs = sess.run([x,w,xwb,s],feed_dict={x:x_data,w:w_data})
        
print(f'outs = {outs}')


outs = [array([[-0.14289442, -1.534281  , -1.0454355 ,  2.180327  , -0.74244404,
         2.0814402 , -0.09684806,  0.81608784,  0.47509065,  0.8519334 ],
       [ 0.56326616,  2.2072134 ,  2.5917482 ,  1.093471  ,  0.06422237,
         0.43132916, -0.8167682 , -0.03857493, -2.013614  ,  0.5137488 ],
       [-0.15031873,  1.2322581 , -0.15338492, -1.5262156 , -0.12875867,
        -0.6426594 , -0.48581013, -0.91131175, -1.1393692 ,  0.01943026],
       [ 0.17589481, -0.49966267,  0.5155953 , -0.42778412, -0.05981462,
        -1.3618331 , -0.27355647,  0.22556332, -0.27806863, -0.19413461],
       [-0.49961042,  0.27111843, -0.00536524,  1.3225477 , -0.42222342,
        -0.1290114 ,  0.6590572 , -0.24185717, -1.3037853 ,  1.8770891 ]],
      dtype=float32), array([[ 0.10551108],
       [-0.1507006 ],
       [ 0.53588796],
       [-0.06253596],
       [ 0.5101545 ],
       [ 1.0689892 ],
       [-0.09796327],
       [ 1.4241843 ],
       [-0.4270514 ],
       [ 0.46021137]], dtype=float32

In [95]:
def standRegree(xArr, yArr):
    xMat = np.mat(xArr)
    yMat = np.mat(yArr).T
    
    xTx = xMat.T*xMat
    if np.linalg.det(xTx) == 0.0:
        print("This matrix is singular")
        return
    ws = xTx.I * (xMat.T*yMat)
    return ws

xArr = np.array([[1,2,3],[1,3,4]])

yArr = np.array([[2,3]])

standRegree(xArr,yArr)

matrix([[ 0.625],
        [ 0.875],
        [-0.875]])

In [98]:
x_data = np.array([[1,2,3],[1,3,4]])
y_data = np.array([[2,3]])


with tf.Graph().as_default():
    x = tf.placeholder(tf.float32, shape=[None,3])
    y = tf.placeholder(tf.float32, shape=None)
    
    w = tf.Variable([[0,0,0]],dtype=tf.float32, name = 'weight')
#     b = tf.Variable(0,dtype=tf.float32, name='bias')
    
    y_hat = tf.matmul(w, tf.transpose(x))  # +b
    
    loss = tf.reduce_mean(tf.square(y-y_hat))
#     cost = tf.Variable(loss, dtype=tf.float32, name='cost')
    
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
    train = optimizer.minimize(loss)
    
    init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(init)
        for step in range(100000):
            sess.run(train, feed_dict={x:x_data,y:y_data})
            if (step % 5000 == 0):
                print(step, sess.run([w]))
        print(step, sess.run([w]))


0 [array([[0.005, 0.013, 0.018]], dtype=float32)]
5000 [array([[-0.01782325,  0.4320007 ,  0.41419315]], dtype=float32)]
10000 [array([[-0.11664751,  0.5054869 ,  0.3888776 ]], dtype=float32)]
15000 [array([[-0.1845196 ,  0.5559487 ,  0.37149733]], dtype=float32)]
20000 [array([[-0.23113608,  0.5906004 ,  0.35956463]], dtype=float32)]
25000 [array([[-0.26315463,  0.61439687,  0.3513718 ]], dtype=float32)]
30000 [array([[-0.28514707,  0.63074017,  0.34574485]], dtype=float32)]
35000 [array([[-0.30025205,  0.6419652 ,  0.34188125]], dtype=float32)]
40000 [array([[-0.31062844,  0.6496772 ,  0.33922562]], dtype=float32)]
45000 [array([[-0.3177552 ,  0.6549742 ,  0.33740252]], dtype=float32)]
50000 [array([[-0.32264894,  0.6586089 ,  0.33615106]], dtype=float32)]
55000 [array([[-0.326013  ,  0.661107  ,  0.33529198]], dtype=float32)]
60000 [array([[-0.32832152,  0.66282684,  0.33469886]], dtype=float32)]
65000 [array([[-0.3299071 ,  0.6640078 ,  0.33429036]], dtype=float32)]
70000 [array([[

In [111]:
f = open('ex1.txt','r')
line = f.readlines()

lst = []

for i in line:
    lst.append(i.split())
    line = f.readlines()
    
f.close()

In [112]:
lst

[['1.000000', '0.635975', '4.093119'],
 ['1.000000', '0.552438', '3.804358'],
 ['1.000000', '0.855922', '4.456531'],
 ['1.000000', '0.083386', '3.187049'],
 ['1.000000', '0.975802', '4.506176'],
 ['1.000000', '0.181269', '3.171914'],
 ['1.000000', '0.129156', '3.053996'],
 ['1.000000', '0.605648', '3.974659'],
 ['1.000000', '0.301625', '3.542525'],
 ['1.000000', '0.698805', '4.234199'],
 ['1.000000', '0.226419', '3.405937'],
 ['1.000000', '0.519290', '3.932469'],
 ['1.000000', '0.354424', '3.514051'],
 ['1.000000', '0.118380', '3.105317'],
 ['1.000000', '0.512811', '3.843351'],
 ['1.000000', '0.236795', '3.576074'],
 ['1.000000', '0.353509', '3.544471'],
 ['1.000000', '0.481447', '3.934625'],
 ['1.000000', '0.060509', '3.228226'],
 ['1.000000', '0.174090', '3.300232'],
 ['1.000000', '0.806818', '4.331785'],
 ['1.000000', '0.531462', '3.908166'],
 ['1.000000', '0.853167', '4.386918'],
 ['1.000000', '0.304804', '3.617260'],
 ['1.000000', '0.612021', '4.082411'],
 ['1.000000', '0.620880',

In [114]:
x_data = [[float(i[0]),float(i[1])] for i in lst]
x_data

[[1.0, 0.635975],
 [1.0, 0.552438],
 [1.0, 0.855922],
 [1.0, 0.083386],
 [1.0, 0.975802],
 [1.0, 0.181269],
 [1.0, 0.129156],
 [1.0, 0.605648],
 [1.0, 0.301625],
 [1.0, 0.698805],
 [1.0, 0.226419],
 [1.0, 0.51929],
 [1.0, 0.354424],
 [1.0, 0.11838],
 [1.0, 0.512811],
 [1.0, 0.236795],
 [1.0, 0.353509],
 [1.0, 0.481447],
 [1.0, 0.060509],
 [1.0, 0.17409],
 [1.0, 0.806818],
 [1.0, 0.531462],
 [1.0, 0.853167],
 [1.0, 0.304804],
 [1.0, 0.612021],
 [1.0, 0.62088],
 [1.0, 0.580245],
 [1.0, 0.742443],
 [1.0, 0.11077],
 [1.0, 0.742687],
 [1.0, 0.57439],
 [1.0, 0.986378],
 [1.0, 0.294867],
 [1.0, 0.472125],
 [1.0, 0.872321],
 [1.0, 0.843537],
 [1.0, 0.864577],
 [1.0, 0.341874],
 [1.0, 0.09798],
 [1.0, 0.757874],
 [1.0, 0.877656],
 [1.0, 0.457993],
 [1.0, 0.475341],
 [1.0, 0.848391],
 [1.0, 0.746059],
 [1.0, 0.153462],
 [1.0, 0.694256],
 [1.0, 0.498712],
 [1.0, 0.02358],
 [1.0, 0.976826],
 [1.0, 0.624004],
 [1.0, 0.47222],
 [1.0, 0.390551],
 [1.0, 0.021349],
 [1.0, 0.173488],
 [1.0, 0.971028],
 

In [115]:
y_data = [float(i[2]) for i in lst]
y_data

[4.093119,
 3.804358,
 4.456531,
 3.187049,
 4.506176,
 3.171914,
 3.053996,
 3.974659,
 3.542525,
 4.234199,
 3.405937,
 3.932469,
 3.514051,
 3.105317,
 3.843351,
 3.576074,
 3.544471,
 3.934625,
 3.228226,
 3.300232,
 4.331785,
 3.908166,
 4.386918,
 3.61726,
 4.082411,
 3.94947,
 3.984041,
 4.251907,
 3.115214,
 4.234319,
 3.947544,
 4.532519,
 3.510392,
 3.927832,
 4.631825,
 4.482263,
 4.487656,
 3.486371,
 3.137514,
 4.21266,
 4.506268,
 3.800973,
 3.975979,
 4.494447,
 4.244715,
 3.019251,
 4.277945,
 3.812414,
 3.116973,
 4.617363,
 4.005158,
 3.874188,
 3.630228,
 3.145849,
 3.192618,
 4.540226,
 3.835879,
 3.141948,
 4.323316,
 4.204829,
 3.94671,
 4.666332,
 3.482348,
 3.451286,
 4.186388,
 3.595223,
 3.534446,
 3.420891,
 4.115553,
 4.257463,
 3.934798,
 4.154963,
 4.58747,
 3.944766,
 3.480517,
 3.481382,
 4.253286,
 3.13167,
 3.527099,
 3.378051,
 4.57896,
 4.551773,
 3.634259,
 4.167016,
 4.21757,
 3.237201,
 4.353163,
 4.342184,
 3.23695,
 3.509404,
 3.242535,
 3.90793

In [116]:
with tf.Graph().as_default():
    x = tf.placeholder(tf.float32, shape=[None,2])
    y = tf.placeholder(tf.float32, shape=None)
    
    w = tf.Variable([[0,0]],dtype=tf.float32, name = 'weight')
#     b = tf.Variable(0,dtype=tf.float32, name='bias')
    
    y_hat = tf.matmul(w, tf.transpose(x))  # +b
    
    loss = tf.reduce_mean(tf.square(y-y_hat))
#     cost = tf.Variable(loss, dtype=tf.float32, name='cost')
    
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
    train = optimizer.minimize(loss)
    
    init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(init)
        for step in range(100000):
            sess.run(train, feed_dict={x:x_data,y:y_data})
            if (step % 5000 == 0):
                print(step, sess.run([w]))
        print(step, sess.run([w]))
        

0 [array([[0.0076501, 0.0040142]], dtype=float32)]
5000 [array([[3.028434 , 1.6291797]], dtype=float32)]
10000 [array([[3.0187156, 1.647771 ]], dtype=float32)]
15000 [array([[3.0135934, 1.6575929]], dtype=float32)]
20000 [array([[3.010817 , 1.6627896]], dtype=float32)]
25000 [array([[3.0094368, 1.6654665]], dtype=float32)]
30000 [array([[3.008629 , 1.6670132]], dtype=float32)]
35000 [array([[3.008276 , 1.6677339]], dtype=float32)]
40000 [array([[3.0081427, 1.6680063]], dtype=float32)]
45000 [array([[3.0081427, 1.6680063]], dtype=float32)]
50000 [array([[3.0081427, 1.6680063]], dtype=float32)]
55000 [array([[3.0081427, 1.6680063]], dtype=float32)]
60000 [array([[3.0081427, 1.6680063]], dtype=float32)]
65000 [array([[3.0081427, 1.6680063]], dtype=float32)]
70000 [array([[3.0081427, 1.6680063]], dtype=float32)]
75000 [array([[3.0081427, 1.6680063]], dtype=float32)]
80000 [array([[3.0081427, 1.6680063]], dtype=float32)]
85000 [array([[3.0081427, 1.6680063]], dtype=float32)]
90000 [array([[