In [40]:
skill = 'CBDK'

skill_trees = ['BACDE','CBADF','AECB','BDA']



def solution(skill,skill_trees)
    answer=0

    for i in skill_trees:
        lst=[]
        for j in range(len(skill)):
            lst.append(i.find(skill[j]))

        a = True
        for j in range(len(skill)-1):
            if (lst[j] == -1) & (lst[j+1] != -1):
                a=False
            elif (lst[j] > lst[j+1]) & (lst[j+1]!=-1):
                a=False
            else:
                pass

        if a == True:
            answer = answer +1

    return answer

print(f'answer is {answer}')

answer is 2


In [2]:
from numpy.random import randn
import numpy as np

data = randn(2,3)
data

array([[0.88816022, 0.55510107, 2.35661119],
       [1.78225216, 1.40622654, 1.46312671]])

In [49]:
data *10

array([[ 8.50938315,  2.84601106, -4.38547547],
       [ 1.07158094,  8.84339033, -0.51245094]])

In [53]:
data+5

array([[5.85093832, 5.28460111, 4.56145245],
       [5.10715809, 5.88433903, 4.94875491]])

In [54]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [55]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
old_values = arr3d[0].copy()

In [58]:
arr3d[0]=42
arr3d


array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[1,0]

array([7, 8, 9])

In [62]:
arr3d[1,0,2]

9

In [3]:
data = randn(7,4)

TF = np.array(['T','T','F','F','T','T','F'])

TF

array(['T', 'T', 'F', 'F', 'T', 'T', 'F'], dtype='<U1')

In [4]:
data

array([[ 0.6909759 ,  2.0413725 , -1.2915753 ,  0.17727669],
       [ 1.09153299, -1.39800575,  0.55187213, -0.08858254],
       [-1.90798677,  0.23779336, -1.12254518,  0.75583444],
       [-0.45659428, -0.86258257, -0.67763721, -0.6914917 ],
       [ 0.12152466,  1.37559433,  0.06036688, -0.2355072 ],
       [ 1.68405578, -3.34074663, -0.47161267, -1.37059563],
       [ 1.05884547, -0.74957957,  0.81196728,  0.13318795]])

In [5]:
data[TF == 'T']

array([[ 0.6909759 ,  2.0413725 , -1.2915753 ,  0.17727669],
       [ 1.09153299, -1.39800575,  0.55187213, -0.08858254],
       [ 0.12152466,  1.37559433,  0.06036688, -0.2355072 ],
       [ 1.68405578, -3.34074663, -0.47161267, -1.37059563]])

In [6]:
data[~(TF=='T')]

array([[-1.90798677,  0.23779336, -1.12254518,  0.75583444],
       [-0.45659428, -0.86258257, -0.67763721, -0.6914917 ],
       [ 1.05884547, -0.74957957,  0.81196728,  0.13318795]])

In [8]:
num = np.array([1,1,0,0,1,1,0])

In [9]:
num

array([1, 1, 0, 0, 1, 1, 0])

In [12]:
data[num]

array([[ 1.09153299, -1.39800575,  0.55187213, -0.08858254],
       [ 1.09153299, -1.39800575,  0.55187213, -0.08858254],
       [ 0.6909759 ,  2.0413725 , -1.2915753 ,  0.17727669],
       [ 0.6909759 ,  2.0413725 , -1.2915753 ,  0.17727669],
       [ 1.09153299, -1.39800575,  0.55187213, -0.08858254],
       [ 1.09153299, -1.39800575,  0.55187213, -0.08858254],
       [ 0.6909759 ,  2.0413725 , -1.2915753 ,  0.17727669]])

In [14]:
data[data<0] =0
data

array([[0.6909759 , 2.0413725 , 0.        , 0.17727669],
       [1.09153299, 0.        , 0.55187213, 0.        ],
       [0.        , 0.23779336, 0.        , 0.75583444],
       [0.        , 0.        , 0.        , 0.        ],
       [0.12152466, 1.37559433, 0.06036688, 0.        ],
       [1.68405578, 0.        , 0.        , 0.        ],
       [1.05884547, 0.        , 0.81196728, 0.13318795]])

In [15]:
data[data>1]=1

In [16]:
data

array([[0.6909759 , 1.        , 0.        , 0.17727669],
       [1.        , 0.        , 0.55187213, 0.        ],
       [0.        , 0.23779336, 0.        , 0.75583444],
       [0.        , 0.        , 0.        , 0.        ],
       [0.12152466, 1.        , 0.06036688, 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.81196728, 0.13318795]])

In [17]:
[0,1,2,3],
[4,5,6,7],
[8,9,10,11]

[0, 1, 2, 3, 4]

In [18]:
[0,1,2],
[3,4,5]

([0], [1])