In [35]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [7]:
x_data = [[1,2,1,1],
          [2,1,3,2],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7],
          [3,1,6,4]]

y_data = [[0,0,1],
          [0,0,1],
          [0,0,1],
          [0,1,0],
          [0,1,0],
          [0,1,0],
          [1,0,0],
          [1,0,0]]

X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,3])

W = tf.Variable(tf.random_normal([4,3]), name = 'weight')
b = tf.Variable(tf.random_normal([3]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
# softmax : 각각의 값을 합으로 나누어줌 ( 확률값으로 변환시켜줌 ) (실제로는 e^i / e^a + e^b + e^c + e^d ...)

cost = tf.reduce_mean(-tf.reduce_mean(Y*tf.log(hypothesis),axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step %200 ==0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
    a = sess.run(hypothesis, feed_dict = {X:[[1,11,7,9]]})
    print(a,sess.run(tf.argmax(a,1)))

0 1.052577
200 0.14730003
400 0.12239289
600 0.109156534
800 0.10008681
1000 0.09322828
1200 0.087758854
1400 0.08324725
1600 0.07943638
1800 0.07615952
2000 0.073302
[[3.7221113e-04 9.9962068e-01 7.0448791e-06]] [1]


In [14]:
zoo = pd.read_csv('data-04-zoo.csv')
zoo= zoo[18:]
zoo

# https://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data  \
18                                                   1                         
19                                                   1                         
20                                                   0                         
21                                                   1                         
22                                                   1                         
..                                                 ...                         
114                                                  1                         
115                                                  1                         
116                                                  1                         
117                                                  0                         
118                                                  0                         

    Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4 Unnamed: 5  Unnamed: 6  \
18           0         0.0         1.0         0.0          0         1.0   
19           0         0.0         1.0         0.0          0         0.0   
20           0         1.0         0.0         0.0          1         1.0   
21           0         0.0         1.0         0.0          0         1.0   
22           0         0.0         1.0         0.0          0         1.0   
..         ...         ...         ...         ...        ...         ...   
114          0         0.0         1.0         0.0          0         0.0   
115          0         1.0         0.0         1.0          0         0.0   
116          0         0.0         1.0         0.0          0         1.0   
117          0         1.0         0.0         0.0          0         0.0   
118          1         1.0         0.0         1.0          0         0.0   

     Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
18          1.0         1.0         1.0          0.0          0.0   
19          1.0         1.0         1.0          0.0          0.0   
20          1.0         1.0         0.0          0.0          1.0   
21          1.0         1.0         1.0          0.0          0.0   
22          1.0         1.0         1.0          0.0          0.0   
..          ...         ...         ...          ...          ...   
114         1.0         1.0         1.0          0.0          0.0   
115         0.0         0.0         1.0          1.0          0.0   
116         1.0         1.0         1.0          0.0          0.0   
117         0.0         0.0         1.0          0.0          0.0   
118         0.0         1.0         1.0          0.0          0.0   

     Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  
18           4.0          0.0          0.0          1.0          0.0  
19           4.0          1.0          0.0          1.0          0.0  
20           0.0          1.0          0.0          0.0          3.0  
21           4.0          0.0          0.0          1.0          0.0  
22           4.0          1.0          0.0          1.0          0.0  
..           ...          ...          ...          ...          ...  
114          2.0          1.0          0.0          1.0          0.0  
115          6.0          0.0          0.0          0.0          5.0  
116          4.0          1.0          0.0          1.0          0.0  
117          0.0          0.0          0.0          0.0          6.0  
118          2.0          1.0          0.0          0.0          1.0  

[101 rows x 17 columns]

In [16]:
x_data = zoo.iloc[:,:-1]
x_data

# https://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data  \
18                                                   1                         
19                                                   1                         
20                                                   0                         
21                                                   1                         
22                                                   1                         
..                                                 ...                         
114                                                  1                         
115                                                  1                         
116                                                  1                         
117                                                  0                         
118                                                  0                         

    Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4 Unnamed: 5  Unnamed: 6  \
18           0         0.0         1.0         0.0          0         1.0   
19           0         0.0         1.0         0.0          0         0.0   
20           0         1.0         0.0         0.0          1         1.0   
21           0         0.0         1.0         0.0          0         1.0   
22           0         0.0         1.0         0.0          0         1.0   
..         ...         ...         ...         ...        ...         ...   
114          0         0.0         1.0         0.0          0         0.0   
115          0         1.0         0.0         1.0          0         0.0   
116          0         0.0         1.0         0.0          0         1.0   
117          0         1.0         0.0         0.0          0         0.0   
118          1         1.0         0.0         1.0          0         0.0   

     Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
18          1.0         1.0         1.0          0.0          0.0   
19          1.0         1.0         1.0          0.0          0.0   
20          1.0         1.0         0.0          0.0          1.0   
21          1.0         1.0         1.0          0.0          0.0   
22          1.0         1.0         1.0          0.0          0.0   
..          ...         ...         ...          ...          ...   
114         1.0         1.0         1.0          0.0          0.0   
115         0.0         0.0         1.0          1.0          0.0   
116         1.0         1.0         1.0          0.0          0.0   
117         0.0         0.0         1.0          0.0          0.0   
118         0.0         1.0         1.0          0.0          0.0   

     Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  
18           4.0          0.0          0.0          1.0  
19           4.0          1.0          0.0          1.0  
20           0.0          1.0          0.0          0.0  
21           4.0          0.0          0.0          1.0  
22           4.0          1.0          0.0          1.0  
..           ...          ...          ...          ...  
114          2.0          1.0          0.0          1.0  
115          6.0          0.0          0.0          0.0  
116          4.0          1.0          0.0          1.0  
117          0.0          0.0          0.0          0.0  
118          2.0          1.0          0.0          0.0  

[101 rows x 16 columns]

In [18]:
y_data = zoo.iloc[:,-1:]
y_data

Unnamed: 16
18           0.0
19           0.0
20           3.0
21           0.0
22           0.0
..           ...
114          0.0
115          5.0
116          0.0
117          6.0
118          1.0

[101 rows x 1 columns]

In [24]:
y_data = pd.get_dummies(y_data.iloc[:,0])

In [25]:
y_data

0.0  1.0  2.0  3.0  4.0  5.0  6.0
18     1    0    0    0    0    0    0
19     1    0    0    0    0    0    0
20     0    0    0    1    0    0    0
21     1    0    0    0    0    0    0
22     1    0    0    0    0    0    0
..   ...  ...  ...  ...  ...  ...  ...
114    1    0    0    0    0    0    0
115    0    0    0    0    0    1    0
116    1    0    0    0    0    0    0
117    0    0    0    0    0    0    1
118    0    1    0    0    0    0    0

[101 rows x 7 columns]

In [34]:
X = tf.placeholder("float",[None,16])
Y = tf.placeholder("float",[None,7])

W = tf.Variable(tf.random_normal([16,7]), name = 'weight')
b = tf.Variable(tf.random_normal([7]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
# softmax : 각각의 값을 합으로 나누어줌 ( 확률값으로 변환시켜줌 ) (실제로는 e^i / e^a + e^b + e^c + e^d ...)

cost = tf.reduce_mean(-tf.reduce_mean(Y*tf.log(hypothesis),axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.05).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(50001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step %10000 ==0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))

0 0.7746314
10000 0.019866748
20000 0.010246677
30000 0.006952424
40000 0.005287031
50000 0.004278982


In [39]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,:-1]
y_data = xy[:,[-1]]

In [41]:
print(x_data.shape)

(101, 16)


In [43]:
X = tf.placeholder(tf.float32, [None,16])
Y = tf.placeholder(tf.int32, [None,1])

Y_one_hot = tf.one_hot(Y,7)

print(Y_one_hot)

Y_one_hot = tf.reshape(Y_one_hot, [-1,7])
# reshape 에서 [-1,7] : 맨뒤를 7로 맞추라, -1은 상관없다는 뜻
# [-1,14] 라면 2개씩 풀어서 맞추게됨


print(Y_one_hot)


Tensor("one_hot_1:0", shape=(?, 1, 7), dtype=float32)
Tensor("Reshape:0", shape=(?, 7), dtype=float32)


In [49]:
W = tf.Variable(tf.random_normal([16,7]), name = 'weight')
b = tf.Variable(tf.random_normal([7]), name = 'bias')


logits = tf.matmul(X,W) +b
hypothesis = tf.nn.softmax(logits)
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels = Y_one_hot)

cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis,1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(optimizer, feed_dict = {X:x_data, Y:y_data})
        if step % 200 ==0:
            loss, acc = sess.run([cost, accuracy], feed_dict={X:x_data, Y:y_data})
            print(step, loss, acc)
    pred = sess.run(prediction, feed_dict={X:x_data})
    for p, y in zip(pred, y_data.flatten()):
        print(f"{p==int(y)}  /  Prediction : {p}  /  True Y : {int(y)}")

0 6.746447 0.11881188
200 0.36133268 0.9108911
400 0.22266765 0.9405941
600 0.15887833 0.980198
800 0.12299032 1.0
1000 0.10030684 1.0
1200 0.084776975 1.0
1400 0.073501185 1.0
1600 0.06494193 1.0
1800 0.05821828 1.0
2000 0.052792467 1.0
True  /  Prediction : 0  /  True Y : 0
True  /  Prediction : 0  /  True Y : 0
True  /  Prediction : 3  /  True Y : 3
True  /  Prediction : 0  /  True Y : 0
True  /  Prediction : 0  /  True Y : 0
True  /  Prediction : 0  /  True Y : 0
True  /  Prediction : 0  /  True Y : 0
True  /  Prediction : 3  /  True Y : 3
True  /  Prediction : 3  /  True Y : 3
True  /  Prediction : 0  /  True Y : 0
True  /  Prediction : 0  /  True Y : 0
True  /  Prediction : 1  /  True Y : 1
True  /  Prediction : 3  /  True Y : 3
True  /  Prediction : 6  /  True Y : 6
True  /  Prediction : 6  /  True Y : 6
True  /  Prediction : 6  /  True Y : 6
True  /  Prediction : 1  /  True Y : 1
True  /  Prediction : 0  /  True Y : 0
True  /  Prediction : 3  /  True Y : 3
True  /  Prediction :

In [59]:
x_data = [[0,0],
         [0,1],
         [1,0],
         [1,1]]

y_data = [[0],
         [1],
         [1],
         [0]]

X = tf.placeholder(tf.float32, shape=[None,2])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([2,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')


hypothesis = tf.sigmoid(tf.matmul(X,W) + b)   #1.0 / (1+ np.exp(-(tf.matmul(X,W)+b)))
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
        if step % 200 == 0:
            print(step, cost_val)
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    
    print(f'\n Hypothesis = \n {h}',
         f'\n\n Predicted =  \n {c}',
         f'\n\n Accuracy = {a}')

0 0.7770369
200 0.75034964
400 0.7363227
600 0.7269579
800 0.7198989
1000 0.7143547
1200 0.7099563
1400 0.70646346
1600 0.7036932
1800 0.70149916
2000 0.6997634
2200 0.69839096
2400 0.6973064
2600 0.696449
2800 0.69577134
3000 0.6952352
3200 0.6948109
3400 0.69447476
3600 0.6942082
3800 0.69399667
4000 0.6938284
4200 0.6936946
4400 0.6935879
4600 0.6935026
4800 0.6934345
5000 0.6933799
5200 0.693336
5400 0.69330084
5600 0.69327235
5800 0.69324946
6000 0.6932309
6200 0.69321585
6400 0.6932036
6600 0.6931937
6800 0.69318557
7000 0.69317895
7200 0.6931735
7400 0.693169
7600 0.69316536
7800 0.6931624
8000 0.69315994
8200 0.69315773
8400 0.693156
8600 0.69315463
8800 0.6931535
9000 0.6931524
9200 0.6931516
9400 0.6931509
9600 0.6931503
9800 0.6931498
10000 0.69314945

 Hypothesis = 
 [[0.49838316]
 [0.4992421 ]
 [0.50025046]
 [0.50110936]] 

 Predicted =  
 [[0.]
 [0.]
 [1.]
 [1.]] 

 Accuracy = 0.5


In [57]:
x_data = [[0,0],
         [0,1],
         [1,0],
         [1,1]]

y_data = [[1,0,0],
         [0,1,0],
         [0,1,0],
         [0,0,1]]


X = tf.placeholder("float",[None,2])
Y = tf.placeholder("float",[None,3])

W = tf.Variable(tf.random_normal([2,3]), name = 'weight')
b = tf.Variable(tf.random_normal([3]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
# softmax : 각각의 값을 합으로 나누어줌 ( 확률값으로 변환시켜줌 ) (실제로는 e^i / e^a + e^b + e^c + e^d ...)

cost = tf.reduce_mean(-tf.reduce_mean(Y*tf.log(hypothesis),axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.05).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(50001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step %10000 ==0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    
    print(f'\n Hypothesis = \n {h}',
         f'\n\n Predicted =  \n {c}',
         f'\n\n Accuracy = {a}')

0 0.5917242
10000 0.054193307
20000 0.027325874
30000 0.017992385
40000 0.01334516
50000 0.010582679

 Hypothesis = 
 [[9.7130078e-01 2.8698757e-02 4.9026676e-07]
 [1.0128711e-02 9.6790612e-01 2.1965224e-02]
 [1.0128853e-02 9.6790445e-01 2.1966811e-02]
 [1.0387693e-07 3.2104138e-02 9.6789575e-01]] 

 Predicted =  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

 Accuracy = 1.0


In [ ]:
x_data = [[0,0],
         [0,1],
         [1,0],
         [1,1]]

y_data = [[0],
         [1],
         [1],
         [0]]


X = tf.placeholder(tf.float32, shape=[None,2])
Y = tf.placeholder(tf.float32, shape=[None,1])

W1 = tf.Variable(tf.random_normal([2,4]), name='weight')
b1 = tf.Variable(tf.random_normal([4]), name = 'bias')
layer1 = tf.sigmoid(tf.matmul(X,W1)+b1)

W2 = tf.Variable(tf.random_normal([4,3]), name='weight')
b2 = tf.Variable(tf.random_normal([3]), name = 'bias')
layer2 = tf.sigmoid(tf.matmul(layer1,W2)+b2)


W3 = tf.Variable(tf.random_normal([3,2]), name='weight')
b3 = tf.Variable(tf.random_normal([2]), name = 'bias')
layer3 = tf.sigmoid(tf.matmul(layer2,W3)+b3)


W4 = tf.Variable(tf.random_normal([2,1]), name='weight')
b4 = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = tf.sigmoid(tf.matmul(layer3,W4) + b4)   #1.0 / (1+ np.exp(-(tf.matmul(X,W)+b)))




cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
            if step % 1000 == 0:
                print(step, cost_val)
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})

        print(f'\n Hypothesis = \n {h}',
             f'\n\n Predicted =  \n {c}',
             f'\n\n Accuracy = {a}')

In [115]:
def ann(a1,a2):

    x_data = [[0,0],
             [0,1],
             [1,0],
             [1,1]]

    y_data = [[0],
             [1],
             [1],
             [0]]


    X = tf.placeholder(tf.float32, shape=[None,2])
    Y = tf.placeholder(tf.float32, shape=[None,1])

    W1 = tf.Variable(tf.random_normal([2,a1]), name='weight')
    b1 = tf.Variable(tf.random_normal([a1]), name = 'bias')
    layer1 = tf.sigmoid(tf.matmul(X,W1)+b1)

    W2 = tf.Variable(tf.random_normal([a1,a2]), name='weight')
    b2 = tf.Variable(tf.random_normal([a2]), name = 'bias')
    layer2 = tf.sigmoid(tf.matmul(layer1,W2)+b2)


    W3 = tf.Variable(tf.random_normal([a2,1]), name='weight')
    b3 = tf.Variable(tf.random_normal([1]), name = 'bias')
    hypothesis = tf.sigmoid(tf.matmul(layer2,W3) + b3)   #1.0 / (1+ np.exp(-(tf.matmul(X,W)+b)))




    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

    train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
    predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
    accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        for step in range(10001):
            cost_val, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
#             if step % 1000 == 0:
#                 print(step, cost_val)
        h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})

#         print(f'\n Hypothesis = \n {h}',
#              f'\n\n Predicted =  \n {c}',
#              f'\n\n Accuracy = {a}')
    return a
    

In [122]:
a1=100
a2=50
a=0
for i in range(10):
    b = ann(a1,a2)
    print(b)
    a +=b
print('layer1: ',a1,'   layer2: ',a2,'   acu:  ',a/10)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
layer1:  100    layer2:  50    acu:   1.0
