In [77]:
import numpy as np


progresses = [93,30,55]

speeds = [1,30,5]


p= np.array(progresses)

s= np.array(speeds)



answer = []

n=0



while sum(answer) < len(p):
    p = p + s
    
    if p[n]>= 100:
        dist = 1
        for i in range(n,len(p)-1):
            if p[i] >= 100:
                dist +=1
                n+=1
            else:
                answer.append(dist)
                break
print(answer)

a
a


KeyboardInterrupt: 

In [71]:

progresses = [93,30,55,12,6,23,7,84]

speeds = [1,30,5,62,12,77,43,12]


progresses = np.array(progresses)

speeds=np.array(speeds)

n=0

if progresses[n] > 50:
    print('a')


a


In [78]:
import numpy as np

def solution(progresses, speeds):
    progresses = np.array(progresses)
    speeds = np.array(speeds)
    answer = []
    n=0
    
    while sum(answer) < len(progresses):
        progresses = progresses + speeds
        
        if progresses[n] >=100:
            dist = 1
            for i in range(n,len(progresses)-1):
                if progresses[i+1] >= 100:
                    dist +=1
                    n +=1
                else:
                    answer.append(dist)
                    break
    return answer

solution([93,30,55],[1,30,5])

[2, 1]

In [79]:
arr = np.arange(10)*100

In [80]:
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [81]:
inds = [7,1,2,6]

arr[inds]

array([700, 100, 200, 600])

In [82]:
arr.take(inds)

array([700, 100, 200, 600])

In [83]:
arr.put(inds,42)

In [84]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [85]:
arr.put(inds,[40,41,42,43])

In [86]:
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [115]:
from numpy import linalg as la
def ecludDist(inA, inB):
    distance = np.sqrt(np.sum((inA-inB)**2,0))
    return distance

In [116]:
inA = np.array([[0,0],[1,1]])
inB = np.array([[3,4],[4,5]])



In [117]:
answer =[]
for i in range(len(inA)):
    answer.append(ecludDist(inA[i],inB[i]))
    

answer

[5.0, 5.0]

In [119]:
group = np.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])

labels = ['A','A','B','B']



In [192]:
def classify0(x,group,labels,k):
    ans=[]

    for i in range(len(group)):
        a = ecludDist(group[i], x)
        ans.append([a,labels[i]])


    ans.sort()


    dict={}

    for i in range(k):
        if ans[i][1] in dict:
            dict[ans[i][1]]+=1
        else:
            dict[ans[i][1]] =1

    maxdict = max(dict, key= lambda x:dict[x])

    return maxdict


In [148]:
x= np.array([0,0])

k=3

ans=[]

for i in range(len(group)):
    a = ecludDist(group[i], x)
    ans.append([a,labels[i]])


ans.sort()


dict={}

for i in range(k):
    if ans[i][1] in dict:
        dict[ans[i][1]]+=1
    else:
        dict[ans[i][1]] =1
        
print(dict)

maxdict = max(dict, key= lambda x:dict[x])

print(maxdict)

{'B': 2, 'A': 1}
B


In [159]:
classify0([10,1],group,labels,3)

{'A': 2, 'B': 1}


'A'

In [172]:
f=open('datingTestSet2.txt','r')

line = f.readline()

data=[]

while line:
    data.append(line.split())
    line=f.readline()

f.close()
    
dataset = np.array(data)


dataset.shape

dataset[0:5,:]

array([['40920', '8.326976', '0.953952', '3'],
       ['14488', '7.153469', '1.673904', '2'],
       ['26052', '1.441871', '0.805124', '1'],
       ['75136', '13.147394', '0.428964', '1'],
       ['38344', '1.669788', '0.134296', '1']], dtype='<U9')

In [174]:
dataset = np.loadtxt("datingTestSet2.txt",delimiter='\t')

dataset[0:5,:]

array([[4.0920000e+04, 8.3269760e+00, 9.5395200e-01, 3.0000000e+00],
       [1.4488000e+04, 7.1534690e+00, 1.6739040e+00, 2.0000000e+00],
       [2.6052000e+04, 1.4418710e+00, 8.0512400e-01, 1.0000000e+00],
       [7.5136000e+04, 1.3147394e+01, 4.2896400e-01, 1.0000000e+00],
       [3.8344000e+04, 1.6697880e+00, 1.3429600e-01, 1.0000000e+00]])

In [208]:
trainData = dataset[:900,:3]
trainLabels = dataset[:900,3]
testData = dataset[900:,:3]
testLabels = dataset[900:,3]

In [181]:
def classify0(x,group,labels,k):
    ans=[]

    for i in range(len(group)):
        a = ecludDist(group[i], x)
        ans.append([a,labels[i]])


    ans.sort()


    dict={}

    for i in range(k):
        if ans[i][1] in dict:
            dict[ans[i][1]]+=1
        else:
            dict[ans[i][1]] =1

    print(dict)

    maxdict = max(dict, key= lambda x:dict[x])

    return maxdict

In [189]:
classify0(testData[0],trainData,trainLabels,30)

{3.0: 1, 2.0: 29}


2.0

In [193]:
def knn(testdata, traindata, trainlabels, k):
    answer=[]
    for i in range(len(testdata)):
        answer.append(classify0(testdata[i],traindata,trainlabels,k))
        
    return answer

In [209]:
a= knn(testData,trainData,trainLabels,30)

print(a)

[3.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 3.0, 3.0, 1.0, 1.0, 1.0, 3.0, 3.0, 3.0, 3.0, 3.0, 2.0, 3.0, 1.0, 3.0, 3.0, 2.0, 3.0, 2.0, 3.0, 3.0, 2.0, 2.0, 3.0, 3.0, 1.0, 1.0, 3.0, 3.0, 1.0, 1.0, 3.0, 3.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 3.0, 2.0, 1.0, 1.0, 2.0, 3.0, 2.0, 2.0, 1.0, 3.0, 1.0, 2.0, 3.0, 1.0, 2.0, 2.0, 2.0, 3.0, 3.0, 2.0, 3.0, 1.0, 1.0, 2.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 3.0, 1.0, 3.0]


In [210]:
len(a)

100

In [211]:
cor = 0
miss = 0

for i in range(len(a)):
    if a[i] == testLabels[i]:
        cor +=1
    else:
        miss +=1
        
print((cor/(cor+miss)))

0.88
