In [28]:
import torch
import random

In [2]:
w = torch.tensor(1.0, requires_grad=True)

a = w*4

l = a**2

l.backward()

print(w.grad)

print(f'l을 w로 미분한 값은 : {w.grad}')

tensor(32.)
l을 w로 미분한 값은 : 32.0


In [3]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
print(x.size())
print(x.shape)
print(x.ndimension())

torch.Size([3, 3])
torch.Size([3, 3])
2


In [22]:
x = torch.unsqueeze(x,0)
print(x.shape)

torch.Size([1, 1, 1, 1, 3, 3])


In [23]:
x = torch.squeeze(x,3)

print(x.shape)

torch.Size([1, 1, 1, 3, 3])


In [24]:
x = x.view(9)
print(x)
print(x.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


In [25]:
w = torch.randn(5,3, dtype=torch.float)

x = torch.tensor([[1.0,2.0], [3.0,4.0],[5.0,6.0]])

print(w,x)

print(w.shape,x.shape)

tensor([[-0.8531,  0.6917,  2.1841],
        [ 0.5856,  0.7122, -2.1384],
        [-0.2038,  0.3334,  1.2990],
        [ 1.9278,  0.6405,  0.7952],
        [-0.4033,  0.5582, -0.1526]]) tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([5, 3]) torch.Size([3, 2])


In [32]:
b = torch.randn(5,2, dtype=torch.float)

print(b,'\n', b.shape, '\n', b.size())

tensor([[ 0.6161,  1.6090],
        [ 0.5998, -0.5630],
        [-0.4153, -0.6153],
        [ 0.5930,  0.6684],
        [-0.7013, -1.3172]]) 
 torch.Size([5, 2]) 
 torch.Size([5, 2])


In [35]:
result = torch.mm(w,x) + b

print(result)

tensor([[12.7587, 15.7742],
        [-7.3702, -9.3736],
        [ 6.8763,  8.1049],
        [ 8.4182, 11.8570],
        [-0.1931, -0.8066]])
