In [1]:
import numpy as np

In [165]:
dataset = np.array(range(1,101))

In [166]:
def test_1_slice(dataset,start,x,y):
    data = []
    for i in range(start-1,len(dataset)-x-y+1):
        data.append(dataset[i:i+x+y])
    data = np.array(data)
    
    x_data = data[:,0:x].reshape(-1,7,1)
    y_data = data[:,x:x+y]
    
    return x_data,y_data
        


In [168]:
test_1_slice(dataset,1,7,3)

(array([[[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7]],
 
        [[ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8]],
 
        [[ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9]],
 
        [[ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]],
 
        [[ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11]],
 
        [[ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12]],
 
        [[ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12],
         [13]],
 
        [[ 8],
         [ 9],
         [10],
         [11],
         [12],
         [13],
         [14]],
 
        [[ 9],
         [10],
         [11],
         [12],
         [13],
         [14],
         [15]],
 
        [[10],
         [11]

In [171]:
x_hat, _ = test_1_slice(dataset,91,7,3)
print(x_hat)

[[[91]
  [92]
  [93]
  [94]
  [95]
  [96]
  [97]]]


In [34]:
x,y = test_1_slice(dataset,7,3)

In [35]:
import numpy as np
from keras.layers import Dense, LSTM, Activation, Dropout
from keras.models import Sequential
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [61]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

model = Sequential()
model.add(LSTM(100, input_shape = (7,1)))
model.add(Dropout(0.2))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3))
model.summary()


model.compile(optimizer='rmsprop', loss = 'msle', metrics = ['mse'])
model.fit(x_train,y_train,epochs=30,validation_split=0.2,batch_size=1)

loss, mse = model.evaluate(x_test,y_test)

x_hat = np.array([[[111+i] for i in range(0,7)]])

y_predict = model.predict(x_hat)


print(f'test loss :    {loss}    mse   :  {mse}')
print(f'y_predict :   {y_predict}')

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 100)               40800     
_________________________________________________________________
dropout_3 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               12928     
_________________________________________________________________
dropout_4 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout_5 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 3)                

In [176]:
dataset = np.array(range(1,118))

In [190]:
def test2_slice(dataset,start,end, x_shape,y):
    x_data = []
    y_data = []
    
    for i in range(start-1,end-1):
        xlst=[]
        ylst=[]
        for j in range(x_shape[0]):
            xlst.append(dataset[i+j:i+j+x_shape[1]])
            ylst.append(dataset[i+j+x_shape[1]+2])
        x_data.append(xlst)
        y_data.append(ylst)
    
    return np.array(x_data).reshape(-1,x_shape[0],x_shape[1],1), np.array(y_data)

In [191]:
a,b=test2_slice(dataset,1,114,(3,7),3)

IndexError: index 117 is out of bounds for axis 0 with size 117

In [179]:
print(a)
print(b)

[[[[  1]
   [  2]
   [  3]
   ...
   [  5]
   [  6]
   [  7]]

  [[  2]
   [  3]
   [  4]
   ...
   [  6]
   [  7]
   [  8]]

  [[  3]
   [  4]
   [  5]
   ...
   [  7]
   [  8]
   [  9]]]


 [[[  2]
   [  3]
   [  4]
   ...
   [  6]
   [  7]
   [  8]]

  [[  3]
   [  4]
   [  5]
   ...
   [  7]
   [  8]
   [  9]]

  [[  4]
   [  5]
   [  6]
   ...
   [  8]
   [  9]
   [ 10]]]


 [[[  3]
   [  4]
   [  5]
   ...
   [  7]
   [  8]
   [  9]]

  [[  4]
   [  5]
   [  6]
   ...
   [  8]
   [  9]
   [ 10]]

  [[  5]
   [  6]
   [  7]
   ...
   [  9]
   [ 10]
   [ 11]]]


 ...


 [[[104]
   [105]
   [106]
   ...
   [108]
   [109]
   [110]]

  [[105]
   [106]
   [107]
   ...
   [109]
   [110]
   [111]]

  [[106]
   [107]
   [108]
   ...
   [110]
   [111]
   [112]]]


 [[[105]
   [106]
   [107]
   ...
   [109]
   [110]
   [111]]

  [[106]
   [107]
   [108]
   ...
   [110]
   [111]
   [112]]

  [[107]
   [108]
   [109]
   ...
   [111]
   [112]
   [113]]]


 [[[106]
   [107]
   [108]
   ...
   [

In [184]:
a,_ = test2_slice(dataset,109,(3,7),3)

In [185]:
print(a)

[]


In [46]:
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ModelCheckpoint

In [62]:
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=50)
mc = ModelCheckpoint('./best_model.h5', monitor='val_loss', mode='min', save_best_only=True)


model.compile(optimizer='adam', loss = 'mse', metrics = ['mse'])
model.fit(x_train, y_train, epochs=200,  

                 batch_size=1, verbose=2, validation_split=0.2,   

                 callbacks=[es, mc])


Epoch 1/200
57/57 - 0s - loss: 113.8941 - mse: 113.8941 - val_loss: 6.0097 - val_mse: 6.0097
Epoch 2/200
57/57 - 0s - loss: 93.3153 - mse: 93.3153 - val_loss: 6.4164 - val_mse: 6.4164
Epoch 3/200
57/57 - 0s - loss: 91.7608 - mse: 91.7608 - val_loss: 17.0984 - val_mse: 17.0984
Epoch 4/200
57/57 - 0s - loss: 100.7894 - mse: 100.7894 - val_loss: 20.4975 - val_mse: 20.4975
Epoch 5/200
57/57 - 0s - loss: 106.1620 - mse: 106.1620 - val_loss: 41.1740 - val_mse: 41.1740
Epoch 6/200
57/57 - 0s - loss: 98.5047 - mse: 98.5047 - val_loss: 15.5689 - val_mse: 15.5689
Epoch 7/200
57/57 - 0s - loss: 73.5054 - mse: 73.5054 - val_loss: 21.8641 - val_mse: 21.8641
Epoch 8/200
57/57 - 0s - loss: 85.6528 - mse: 85.6528 - val_loss: 5.3627 - val_mse: 5.3627
Epoch 9/200
57/57 - 0s - loss: 106.8669 - mse: 106.8669 - val_loss: 17.8989 - val_mse: 17.8989
Epoch 10/200
57/57 - 0s - loss: 52.0647 - mse: 52.0647 - val_loss: 2.9290 - val_mse: 2.9290
Epoch 11/200
57/57 - 0s - loss: 101.7196 - mse: 101.7196 - val_loss: 

Epoch 89/200
57/57 - 0s - loss: 104.7727 - mse: 104.7727 - val_loss: 17.8332 - val_mse: 17.8332
Epoch 90/200
57/57 - 0s - loss: 102.3087 - mse: 102.3087 - val_loss: 24.7988 - val_mse: 24.7988
Epoch 91/200
57/57 - 0s - loss: 47.5457 - mse: 47.5457 - val_loss: 11.0866 - val_mse: 11.0866
Epoch 92/200
57/57 - 0s - loss: 80.2010 - mse: 80.2010 - val_loss: 8.4401 - val_mse: 8.4401
Epoch 93/200
57/57 - 0s - loss: 40.3756 - mse: 40.3756 - val_loss: 1.8556 - val_mse: 1.8556
Epoch 94/200
57/57 - 0s - loss: 64.5522 - mse: 64.5522 - val_loss: 5.1625 - val_mse: 5.1625
Epoch 95/200
57/57 - 0s - loss: 68.4176 - mse: 68.4176 - val_loss: 4.8107 - val_mse: 4.8107
Epoch 96/200
57/57 - 0s - loss: 109.9704 - mse: 109.9704 - val_loss: 64.0521 - val_mse: 64.0521
Epoch 97/200
57/57 - 0s - loss: 109.1821 - mse: 109.1821 - val_loss: 51.6407 - val_mse: 51.6407
Epoch 98/200
57/57 - 0s - loss: 65.9830 - mse: 65.9830 - val_loss: 24.3615 - val_mse: 24.3615
Epoch 99/200
57/57 - 0s - loss: 65.9851 - mse: 65.9851 - val

In [63]:
loss, mse = model.evaluate(x_test,y_test)

x_hat = np.array([[[111+i] for i in range(0,7)]])

y_predict = model.predict(x_hat)


print(f'test loss :    {loss}    mse   :  {mse}')
print(f'y_predict :   {y_predict}')

1/1 [==============================] - 0s 2ms/step - loss: 3.3895 - mse: 3.3895
test loss :    3.3895139694213867    mse   :  3.3895139694213867
y_predict :   [[97.58179 98.04633 99.33859]]


In [79]:
import numpy as np
from keras.layers import Dense, LSTM, Activation, Dropout
from keras.models import Sequential
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint,ReduceLROnPlateau


dataset = np.array(range(1,101))

def test_1_slice(dataset,x,y):
    data = []
    for i in range(len(dataset)-x-y+1):
        data.append(dataset[i:i+x+y])
    data = np.array(data)
    
    x_data = data[:,0:x].reshape(-1,7,1)
    y_data = data[:,x:x+y]
    
    return x_data,y_data

x,y = test_1_slice(dataset,7,3)


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

model = Sequential()
model.add(LSTM(30, input_shape = (7,1)))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3))
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=50)
mc = ModelCheckpoint('./best_model.h5', monitor='val_loss', mode='min', save_best_only=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=20, verbose=1, mode='min')



model.compile(optimizer='adam', loss = 'mse')
model.fit(x_train,y_train,epochs=500,validation_split=0.2,batch_size=1,
            verbose=2,callbacks=[es, mc,reduce_lr])

loss = model.evaluate(x_test,y_test)

x_hat = np.array([[[111+i] for i in range(0,7)]])

y_predict = model.predict(x_hat)


print(f'test loss :    {loss}')
print(f'y_predict :   {y_predict}')

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_11 (LSTM)               (None, 30)                3840      
_________________________________________________________________
dropout_33 (Dropout)         (None, 30)                0         
_________________________________________________________________
dense_33 (Dense)             (None, 64)                1984      
_________________________________________________________________
dropout_34 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_34 (Dense)             (None, 32)                2080      
_________________________________________________________________
dropout_35 (Dropout)         (None, 32)                0         
_________________________________________________________________
dense_35 (Dense)             (None, 3)               

Epoch 91/500
57/57 - 0s - loss: 85.6787 - val_loss: 5.2103 - lr: 4.0000e-05
Epoch 92/500
57/57 - 0s - loss: 92.5114 - val_loss: 6.9857 - lr: 4.0000e-05
Epoch 93/500
57/57 - 0s - loss: 124.3060 - val_loss: 1.9566 - lr: 4.0000e-05
Epoch 94/500
57/57 - 0s - loss: 94.7114 - val_loss: 1.2500 - lr: 4.0000e-05
Epoch 95/500
57/57 - 0s - loss: 93.3966 - val_loss: 2.0566 - lr: 4.0000e-05
Epoch 96/500
57/57 - 0s - loss: 91.9939 - val_loss: 2.5354 - lr: 4.0000e-05
Epoch 97/500
57/57 - 0s - loss: 104.0391 - val_loss: 3.0205 - lr: 4.0000e-05
Epoch 98/500

Epoch 00098: ReduceLROnPlateau reducing learning rate to 8.000000525498762e-06.
57/57 - 0s - loss: 83.9463 - val_loss: 2.0982 - lr: 4.0000e-05
Epoch 99/500
57/57 - 0s - loss: 153.7592 - val_loss: 3.0680 - lr: 8.0000e-06
Epoch 100/500
57/57 - 0s - loss: 113.9750 - val_loss: 3.6836 - lr: 8.0000e-06
Epoch 101/500
57/57 - 0s - loss: 76.3794 - val_loss: 3.8309 - lr: 8.0000e-06
Epoch 102/500
57/57 - 0s - loss: 83.6072 - val_loss: 3.8831 - lr: 8.0000e-06


In [159]:
import numpy as np
from keras.layers import Dense, LSTM, Activation, Dropout
from keras.models import Sequential
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint,ReduceLROnPlateau

dataset = np.array(range(1,118))

def test_2_slice(dataset, x_shape,y):
    x_data = []
    y_data = []
    
    for i in range(len(dataset)-x_shape[0]-x_shape[1]-y+2):
        xlst=[]
        ylst=[]
        for j in range(x_shape[0]):
            xlst.append(dataset[i+j:i+j+x_shape[1]])
            ylst.append(dataset[i+j+x_shape[1]+2])
        x_data.append(xlst)
        y_data.append(ylst)
    
    return np.array(x_data), np.array(y_data)


x,y = test_2_slice(dataset,(3,7),3)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

model = Sequential()
model.add(LSTM(30, input_shape = (3,7)))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3))
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=50)
mc = ModelCheckpoint('./best_model.h5', monitor='val_loss', mode='min', save_best_only=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=20, verbose=1, mode='min')



model.compile(optimizer='adam', loss = 'mse')
model.fit(x_train,y_train,epochs=500,validation_split=0.2,batch_size=1,
            verbose=2,callbacks=[es, mc,reduce_lr])

loss = model.evaluate(x_test,y_test)

x_hat = np.array([[109+i+j for i in range(0,7)]for j in range(0,3)]).reshape(-1,3,7)

y_predict = model.predict(x_hat)


print(f'test loss :    {loss}')
print(f'y_predict :   {y_predict}')


Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_18 (LSTM)               (None, 30)                4560      
_________________________________________________________________
dropout_51 (Dropout)         (None, 30)                0         
_________________________________________________________________
dense_51 (Dense)             (None, 64)                1984      
_________________________________________________________________
dropout_52 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_52 (Dense)             (None, 32)                2080      
_________________________________________________________________
dropout_53 (Dropout)         (None, 32)                0         
_________________________________________________________________
dense_53 (Dense)             (None, 3)               

Epoch 90/500
67/67 - 0s - loss: 173.8295 - val_loss: 39.1604 - lr: 4.0000e-05
Epoch 91/500
67/67 - 0s - loss: 165.6468 - val_loss: 26.3117 - lr: 4.0000e-05
Epoch 92/500
67/67 - 0s - loss: 130.3436 - val_loss: 30.6750 - lr: 4.0000e-05
Epoch 93/500
67/67 - 0s - loss: 127.9763 - val_loss: 41.9701 - lr: 4.0000e-05
Epoch 94/500
67/67 - 0s - loss: 141.1998 - val_loss: 39.1333 - lr: 4.0000e-05
Epoch 95/500
67/67 - 0s - loss: 162.8051 - val_loss: 21.1615 - lr: 4.0000e-05
Epoch 96/500
67/67 - 0s - loss: 211.4203 - val_loss: 48.8525 - lr: 4.0000e-05
Epoch 97/500
67/67 - 0s - loss: 146.8564 - val_loss: 41.1188 - lr: 4.0000e-05
Epoch 98/500
67/67 - 0s - loss: 244.5385 - val_loss: 31.4316 - lr: 4.0000e-05
Epoch 99/500
67/67 - 0s - loss: 123.5300 - val_loss: 16.6992 - lr: 4.0000e-05
Epoch 100/500
67/67 - 0s - loss: 134.2956 - val_loss: 55.1583 - lr: 4.0000e-05
Epoch 101/500
67/67 - 0s - loss: 120.8281 - val_loss: 56.3564 - lr: 4.0000e-05
Epoch 102/500
67/67 - 0s - loss: 154.6687 - val_loss: 81.8157 

In [158]:
x

array([[[  1,   2,   3, ...,   5,   6,   7],
        [  2,   3,   4, ...,   6,   7,   8],
        [  3,   4,   5, ...,   7,   8,   9]],

       [[  2,   3,   4, ...,   6,   7,   8],
        [  3,   4,   5, ...,   7,   8,   9],
        [  4,   5,   6, ...,   8,   9,  10]],

       [[  3,   4,   5, ...,   7,   8,   9],
        [  4,   5,   6, ...,   8,   9,  10],
        [  5,   6,   7, ...,   9,  10,  11]],

       ...,

       [[104, 105, 106, ..., 108, 109, 110],
        [105, 106, 107, ..., 109, 110, 111],
        [106, 107, 108, ..., 110, 111, 112]],

       [[105, 106, 107, ..., 109, 110, 111],
        [106, 107, 108, ..., 110, 111, 112],
        [107, 108, 109, ..., 111, 112, 113]],

       [[106, 107, 108, ..., 110, 111, 112],
        [107, 108, 109, ..., 111, 112, 113],
        [108, 109, 110, ..., 112, 113, 114]]])

In [157]:
x_hat

array([[109, 110, 111, 112, 113, 114, 115],
       [110, 111, 112, 113, 114, 115, 116],
       [111, 112, 113, 114, 115, 116, 117]])

In [ ]:
predict_dataset = np.array()