In [170]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation

import pandas as pd
import numpy as np

In [162]:
x_data = np.array([1,2,3,4,5,6,7,8,9,10])

In [176]:
y_data = np.array([1,2,3,4,5,1,2,3,4,5])

In [179]:
y_data = pd.get_dummies(y_data)

In [186]:
np.array(y_data)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [187]:
type(y_data)

pandas.core.frame.DataFrame

In [188]:
x_train = x_data[:8]
x_test = x_data[8:]

y_train = y_data[:8]
y_test = y_data[8:]

In [189]:
model = Sequential()
model.add(Dense(100, input_dim= 1, activation = 'softmax'))
model.add(Dense(50, activation = 'softmax'))
model.add(Dense(1, activation = 'softmax'))

In [190]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam')
model.fit(x_train, y_train, validation_split = 0.2, batch_size=8, epochs=100)

ValueError: Failed to find data adapter that can handle input: <class 'numpy.ndarray'>, <class 'pandas.core.frame.DataFrame'>

In [156]:
mse = model.evaluate(x_test, y_test, batch_size = 1)
print(mse)

2/1 [============================================================] - 0s 23ms/sample - loss: 0.5549
0.9352755174040794


In [157]:
y_predict = model.predict(x_test)
y_predict

array([[0.18341817],
       [0.16017713]], dtype=float32)

In [79]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
model.summary()

Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_42 (Dense)             (None, 10)                20        
_________________________________________________________________
dense_43 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_44 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_45 (Dense)             (None, 1)                 11        
Total params: 251
Trainable params: 251
Non-trainable params: 0
_________________________________________________________________


c:\users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

0.5
0.5
