## bitcoin 예측

In [2]:
get_ipython().run_line_magic('matplotlib', 'inline')
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import numpy as np
# import plotly as py
# import plotly.graph_objs as go
import requests
from keras.layers import *
from keras.models import *
from keras.callbacks import *
from datetime import datetime
from sklearn.preprocessing import MinMaxScaler
plt.style.use('bmh')
'''
https://poloniex.com/public?
command=returnChartData&currencyPair=USDT_BTC&
start=1405699200&end=9999999999&period=14400
'''

'\nhttps://poloniex.com/public?\ncommand=returnChartData&currencyPair=USDT_BTC&\nstart=1405699200&end=9999999999&period=14400\n'

In [4]:
ret = requests.get('https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&start=1405699200&end=9999999999&period=86400')
print(ret)

<Response [200]>


In [5]:
js = ret.json()
print(js)

[{'date': 1424304000, 'high': 244, 'low': 225, 'open': 225, 'close': 244, 'volume': 46.27631267, 'quoteVolume': 0.19311748, 'weightedAverage': 239.62777823}, {'date': 1424390400, 'high': 245, 'low': 240.25, 'open': 240.25011809, 'close': 240.25, 'volume': 55.894897, 'quoteVolume': 0.23042935, 'weightedAverage': 242.56847926}, {'date': 1424476800, 'high': 245, 'low': 245, 'open': 245, 'close': 245, 'volume': 14.72223865, 'quoteVolume': 0.06009077, 'weightedAverage': 245}, {'date': 1424563200, 'high': 249, 'low': 235, 'open': 245, 'close': 235, 'volume': 129.12124785, 'quoteVolume': 0.53905499, 'weightedAverage': 239.53260845}, {'date': 1424649600, 'high': 235.001, 'low': 235, 'open': 235.00000236, 'close': 235, 'volume': 96.56756248, 'quoteVolume': 0.41092569, 'weightedAverage': 235.00006166}, {'date': 1424736000, 'high': 239.75, 'low': 235, 'open': 235, 'close': 239.75, 'volume': 149.15439319, 'quoteVolume': 0.6267487, 'weightedAverage': 237.98117682}, {'date': 1424822400, 'high': 239.

In [6]:
df = pd.DataFrame(js)
scaler = MinMaxScaler()
df[['close']] = scaler.fit_transform(df[['close']])
print(df)

            date          high           low          open     close  \
0     1424304000    244.000000    225.000000    225.000000  0.003428   
1     1424390400    245.000000    240.250000    240.250118  0.003231   
2     1424476800    245.000000    245.000000    245.000000  0.003480   
3     1424563200    249.000000    235.000000    245.000000  0.002955   
4     1424649600    235.001000    235.000000    235.000002  0.002955   
...          ...           ...           ...           ...       ...   
1986  1595894400  11234.275442  10540.000000  11033.360729  0.563342   
1987  1595980800  11333.563609  10829.899891  10905.337547  0.573523   
1988  1596067200  11167.000000  10834.875689  11098.512083  0.573409   
1989  1596153600  11440.348199  10961.176767  11098.889665  0.585878   
1990  1596240000  11741.397100  11224.335824  11333.978175  0.597449   

            volume  quoteVolume  weightedAverage  
0     4.627631e+01     0.193117       239.627778  
1     5.589490e+01     0.230429  

In [7]:
price = df['close'].values.tolist()
print(price)

[0.0034278368698297933, 0.0032309273586996947, 0.0034803460727978203, 0.0029552540431175573, 0.0029552540431175573, 0.003204672757215681, 0.003099654351279629, 0.00313903625350565, 0.003690382884669925, 0.003217803221637167, 0.003795401290605977, 0.004740566944030449, 0.004647100562222272, 0.005318168176678739, 0.004110462809518489, 0.004267984117318213, 0.0042679843914162525, 0.004267985745628597, 0.004478021209064372, 0.0058957694093270275, 0.005108131365331727, 0.00510813142361694, 0.005061398178890919, 0.005060873101038725, 0.005428857595438652, 0.005055622161838608, 0.005055622163413884, 0.00437772835204648, 0.0045224602637016775, 0.004454960511881502, 0.004435645089785174, 0.004662687837208973, 0.004303349663071908, 0.003350412436521174, 0.0036103333860821093, 0.0033504120500534394, 0.003918939692428852, 0.00367612641447527, 0.00363626322497196, 0.003971453807632816, 0.0037081588072975617, 0.003690382884669925, 0.004005438102478082, 0.004005438102478082, 0.003975359605978291, 0.0

In [8]:
window_size = 5
x = []
y = []

for i in range(len(price) - window_size):
    x.append([price[i+j] for j in range(window_size)])
    y.append(price[window_size + i])
    
print(x)
print(y)

[[0.0034278368698297933, 0.0032309273586996947, 0.0034803460727978203, 0.0029552540431175573, 0.0029552540431175573], [0.0032309273586996947, 0.0034803460727978203, 0.0029552540431175573, 0.0029552540431175573, 0.003204672757215681], [0.0034803460727978203, 0.0029552540431175573, 0.0029552540431175573, 0.003204672757215681, 0.003099654351279629], [0.0029552540431175573, 0.0029552540431175573, 0.003204672757215681, 0.003099654351279629, 0.00313903625350565], [0.0029552540431175573, 0.003204672757215681, 0.003099654351279629, 0.00313903625350565, 0.003690382884669925], [0.003204672757215681, 0.003099654351279629, 0.00313903625350565, 0.003690382884669925, 0.003217803221637167], [0.003099654351279629, 0.00313903625350565, 0.003690382884669925, 0.003217803221637167, 0.003795401290605977], [0.00313903625350565, 0.003690382884669925, 0.003217803221637167, 0.003795401290605977, 0.004740566944030449], [0.003690382884669925, 0.003217803221637167, 0.003795401290605977, 0.004740566944030449, 0.00

In [9]:
x = np.asarray(x)
y = np.asarray(y)
print(x)
print(y)

[[0.00342784 0.00323093 0.00348035 0.00295525 0.00295525]
 [0.00323093 0.00348035 0.00295525 0.00295525 0.00320467]
 [0.00348035 0.00295525 0.00295525 0.00320467 0.00309965]
 ...
 [0.49996673 0.51197917 0.56947964 0.56334182 0.57352256]
 [0.51197917 0.56947964 0.56334182 0.57352256 0.57340944]
 [0.56947964 0.56334182 0.57352256 0.57340944 0.58587771]]
[0.00320467 0.00309965 0.00313904 ... 0.57340944 0.58587771 0.59744884]


In [10]:
train_test_split = 1000

x_train = x[:train_test_split, :]
y_train = y[:train_test_split]

x_test = x[train_test_split:, :]
y_test = y[train_test_split :]

print(x_test.shape)
# (566, 5)

print(x_train[0])

(986, 5)
[0.00342784 0.00323093 0.00348035 0.00295525 0.00295525]


## 모델링

In [18]:
model = Sequential()
# model.add(LSTM(128, input_shape=(5,1,)))
model.add(LSTM(128,activation='tanh', input_shape=(5,1),return_sequences=False))
model.add(Dropout(0,2))
model.add(Dense(1, activation='linear'))
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 128)               66560     
_________________________________________________________________
dropout_3 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 129       
Total params: 66,689
Trainable params: 66,689
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(x_train, y_train, epochs=100, batch_size=10)

ValueError: Error when checking input: expected lstm_3_input to have 3 dimensions, but got array with shape (1000, 5)

In [ ]:
train_predict = model.predict(x_train)
test_predict = model.predict(x_test)

plt.figure(figsize=(10,10))
plt.plot(price)

split_pt = train_test_split + window_size
plt.plot(np.arange(window_size, split_pt, 1), train_predict, color='g')

plt.plot(np.arange(split_pt, split_pt + len(test_predict), 1), test_predict, color='r')